global:
  domain: argocd.jakobjkolb.xyz

configs:
  params:
    server.insecure: true
  cm:
    url: "https://argocd.jakobjkolb.xyz"
    admin.enabled: "false"
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $github.clientID
            clientSecret: $github.clientSecret
            redirectURI: https://argocd.jakobjkolb.xyz/api/dex/callback
  rbac:
    policy.default: role:readonly
    scopes: '[groups, email]'
    policy.csv: |
      g, jakob.j.kolb@gmail.com, role:admin

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.jakobjkolb.xyz
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"

  # Disable TLS on the server itself since nginx handles it via passthrough
  extraArgs:
    - --insecure   # remove this if you want end-to-end TLS
